version: '3'
services:
  mysql-db-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wYXNzd29yZCJ9
      - MYSQL_DATABASE=items_db
      - MYSQL_USER=joicm9vdCJ9
      - MYSQL_PASSWORD=wYXNzd29yZCJ9
    ports:
      - "3306:3306"
  challenge-seg360:
    image: challenge-seg360:latest
    build: ./
    depends_on:
      - mysql-db-service
    ports:
      - "8060:8085"
    restart: unless-stopped
 