version: '3.1'
services:
  postgresql-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=items_db
  challenge-seg360:
    image: challenge-seg360:latest
    container_name: challenge-seg360
    build: ./
    depends_on:
      - postgresql-db
    ports:
      - "8060:8085"
    restart: unless-stopped
volumes:
  postgres-data:
 